#!/usr/bin/env ruby

load File.join(ENV['TODO_ACTIONS_DIR'], "show")

all_tasks = Tasks.new.tasks

jobs = ARGV[1..-1].collect{|j| j.to_i }

todo_tasks = Tasks.from_string(open(ENV['TODO_FILE']).read)

tasks = todo_tasks.select{|lno, pri, task| task !~ /^x /}.collect{|x| x[0]}    if todo_tasks

done_file = File.join(ENV['TODO_DIR'], 'done.txt')

jobs.each{|j|
    if tasks.include? j
        system("#{ENV['TODO_SH']} command do #{j}")
    else
        job = all_tasks.select{|x| x[0] == j && x[2] !~ /^x /}    # in current job list
        next if job.empty?
        job = job.first
        next if `grep "#{Time.now.strftime("%Y-%m-%d")} #{job[2]}" #{done_file}|wc -l`.strip == '1'
        #add and do
        system("#{ENV['TODO_SH']} command add #{job[2]}")
        system("#{ENV['TODO_SH']} command do #{todo_tasks.size + 1}")
    end
}
