#!/usr/bin/env ruby
# coding: utf-8
#Author: Roy L Zuo (roylzuo at gmail dot com)
#Description: 

def usage
    puts "   show "
    puts "     shows todo list and calendar entries according to patterns defined."
end

class Tasks
    attr_accessor :tasks

    def self.from_string(string)
        tasks = []

        lno = 0
        string.each_line do |l|
            l.strip!
            next    if l.empty?
            lno += 1
            pri = 0.0
            @@pat_rules.each {|pat, color, contri| pri += contri  if l =~ pat }
            tasks << [ lno, pri, l]
        end
        tasks
    end

    def self.read_rules(rules_file=File.join(ENV['TODO_ACTIONS_DIR'],'show.rc'))
        pri_rules = []
        pat_rules = []

        lno = 0
        IO.foreach(rules_file) do |l|
            l.strip!
            lno += 1 
            next    if l =~ /^#/ || l.empty?
            items = l.split(/\s*,\s*/)
            case items.size
            when 2
                if items.first =~ /\/.*\//
                    pri_rules << [ eval( "proc {|pri, task| task =~ #{items.first} }" ), items.last ]
                else
                    pri_rules << [ eval( "proc {|pri, task| pri #{items.first} }" ), items.last ]
                end
            when 3
                pat_rules << [ eval( items.first ), items[1], items.last.to_f ]
            else
                raise "Invalid pattern on line #{lno}"
            end
        end
        [pri_rules, pat_rules]
    end

    def self.from_a(a)
        new = Tasks.new
        new.tasks = a
        new
    end

    @@pri_rules, @@pat_rules = read_rules

    def read_all
        @tasks = Tasks.from_string(open(ENV['TODO_FILE']).read)
        self << Tasks.from_string(`rem |grep -E '^(T|D|G): '`)
        sort!
        @tasks
    end

    def sort!
        @tasks.sort!{|x,y| 
            projx = x[2].scan(/(?: (\+\w+)|^(\+\w+))/).join
            projy = y[2].scan(/(?: (\+\w+)|^(\+\w+))/).join
            # priority desc, project, line number asc
            [y[1],projx, x[0]] <=> [x[1],projy,y[0]]
        }
    end

    def grep(exp)
        a = @tasks.select{|lno, pri, l| l =~ /#{exp}/i }
        Tasks.from_a(a)
    end

    def <<( list )
        @tasks += list.collect{|lno, pri, l| [lno + @tasks.size, pri, l]}
        clean
    end

    def clean
        todo_compeleted = @tasks.collect{|x| x[2] }
        today = Time.now.strftime("%Y-%m-%d")
        done_file = File.join(ENV['TODO_DIR'], 'done.txt')
        @tasks.delete_if do |lno, pri, l|
            next    if l =~ /^x /
            in_todo = todo_compeleted.include?("x #{today} #{l}")
            in_done = (`grep "#{today} #{l}" #{done_file}|wc -l`.strip == '1')
            in_done or in_todo
        end
    end

    def show
        reset = "\e[m"
        @tasks.each do |lno, pri, task|
            pri_c = "\e[m"
            @@pri_rules.each{|r, c| 
                if r.call(pri, task)
                    pri_c = "\e[#{c}m"; break
                end
            }
            @@pat_rules.each{|pat, col, pri|
                if task =~ pat
                    task.gsub!(pat){|match| 
                        if $1
                            mid = $1
                            pre, post = match.split mid
                            "#{pre}#{reset}\e[#{col}m#{mid}#{reset}#{pri_c}#{post}"
                        else
                            "#{reset}\e[#{col}m#{match}#{reset}#{pri_c}"
                        end
                    }
                end
            }
            puts " \e[36m%-4d\e[m#{pri_c}#{task}#{reset}" %lno
        end
    end
end

if __FILE__==$0
    ARGV.shift  if ARGV.first == File.basename( $0 )
    
    if ARGV.first == "usage"
        usage
    else
        tasks = Tasks.new
        tasks.read_all
        tasks = tasks.grep(ARGV.join(" "))  unless ARGV.empty?
        tasks.show
    end
end
