#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "  start ITEM#..."
    echo "    start an todo item marked as \"WAIT\" or \"MAYBE\""
    exit
}

for i in "$@"; do
    $TODO_SH command replace $i `sed -n "${i}p" $TODO_FILE|sed -r "s:(MAYBE|WAITING|WAIT) ?::"` 2>/dev/null
done
