#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "  start ITEM#..."
    echo "    start an todo item marked as \"WAIT\" or \"MAYBE\""
    exit
}

for i in "$@"; do
    line=`sed -n "${i}p" $TODO_FILE`
    $TODO_SH command replace $i `echo $line|sed -r "s:(MAYBE|WAITING|WAIT)( [0-9]{4}-[0-9]{2}-[0-9]{2})? ?::"` 2>/dev/null
done
