#!/bin/bash
# description: 显示脚本的功能

[[ $1 == "" ]] && folder=~/bin || folder=$1

for f in $folder/*; do
    of=$f
    if [[ -h $f ]]; then
        f=`realpath $f`
    fi
    if [[ -f $f ]] && [[ -x $f ]] && !( file $f|grep ELF &>/dev/null ); then
        desc=`awk -F: 'NR<5 && /[Dd]escription:/ {print $2}' $f`
        printf "%-30s $desc\n" `basename $of`
    fi
done
